-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender,
SUM(purchase_amount) as revenue
FROM  customer
GROUP BY gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5

-- Q4. Compare the average purchase amounts between standard and express shipping
SELECT shipping_type,
AVG(purchase_amount) 
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

-- Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscibers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) AS total_customer,
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status 
ORDER BY total_revenue DESC ,avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into new,returning,and loyal based on their total number of previous purchases,and show the count of each segment
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE
   WHEN previous_purchases = 1 THEN 'New'
   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END AS customer_segment
from customer   
)
SELECT customer_segment,
COUNT(customer_segment) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment

-- Q8.What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

-- select * from customer limit 5;